#!/bin/sh
source ./.aosbuild

aos_compiler ${CC:-clang}
aos_cflags -march=native -std=c99 -Os -pipe -Wall -Wextra -Werror -pedantic
aos_lflags $CFLAGS
aos_pkg sqlite3 yajl libcurl
aos_bin poniko3
aos_src src/*.c

aos_main $@
